# import wikipedia


SECTIONS = {
    # Too unreliable:
    # "discworld": wikipedia.search("discworld novel", results=500),
    # Source: https://en.wikipedia.org/wiki/Category:Discworld_books
    "Discworld": (
        "The Amazing Maurice and His Educated Rodents",
        "The Art of Discworld",
        "A Blink of the Screen",
        "Carpe Jugulum",
        "The Colour of Magic",
        "Death's Domain",
        "The Discworld Almanak",
        "The Discworld Companion",
        "Discworld Diary",
        "Equal Rites",
        "Eric (novel)",
        "Feet of Clay (novel)",
        "The Fifth Elephant",
        "Going Postal",
        "Guards! Guards!",
        "A Hat Full of Sky",
        "Hogfather",
        "I Shall Wear Midnight",
        "Interesting Times",
        "Jingo (novel)",
        "The Last Continent",
        "The Last Hero",
        "The Light Fantastic",
        "Lords and Ladies (novel)",
        "Making Money",
        "The Discworld Mapp",
        "Maskerade",
        "Men at Arms",
        "Monstrous Regiment (novel)",
        "Mort",
        "Moving Pictures (novel)",
        "Nanny Ogg's Cookbook",
        "Night Watch (Discworld)",
        "Once More* with Footnotes",
        "The Pratchett Portfolio",
        "Pyramids (novel)",
        "Raising Steam",
        "Reaper Man",
        "The Science of Discworld",
        "The Science of Discworld II: The Globe",
        "The Science of Discworld III: Darwin's Watch",
        "The Science of Discworld IV: Judgement Day",
        "The Shepherd's Crown",
        "Small Gods",
        "Snuff (Pratchett novel)",
        "Soul Music (novel)",
        "Sourcery",
        "The Streets of Ankh-Morpork",
        "Thief of Time",
        "Thud!",
        "A Tourist Guide to Lancre",
        "The Truth (novel)",
        "Unseen Academicals",
        "The Unseen University Challenge",
        "The Unseen University Cut Out Book",
        "The Wee Free Men",
        "Where's My Cow?",
        "Wintersmith",
        "The Wit and Wisdom of Discworld",
        "Witches Abroad",
        "The World of Poo",
        "Wyrd Sisters",
    ),
}
